- name: "Add Rackspace Cloud Monitoring Apt Key"
  apt_key:
    state: present
    url: "https://monitoring.api.rackspacecloud.com/pki/agent/linux.asc"

- name: "Add Rackspace Cloud Monitoring Archive"
  apt_repository:
    state: present
    repo: "deb http://stable.packages.cloudmonitoring.rackspace.com/ubuntu-14.04-x86_64 cloudmonitoring main"
    update_cache: yes

- name: "Install Rackspace Monitoring Agent"
  apt:
    state: present
    name: rackspace-monitoring-agent
